variables:
  DOCKER_CONTAINER: ${CI_COMMIT_BRANCH}-${CI_PROJECT_NAME}
  DOCKER_IMAGE: ${CI_PROJECT_NAME}:${CI_COMMIT_BRANCH}_${CI_COMMIT_SHA}
  
  CPU_COUNT: 8
  CPU_SHARES: 4096

stages:
  - build
  - deploy


# Build jobs

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
  tags:
    - housing-service
  only:
    - main
    - development


# Deploy jobs

production_deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none

    INTERNAL_NETWORK_NAME: midtob-internal
    INTERNAL_STATIC_IP: 172.18.0.38
    PORT: 9006

    DATABASE_URL: jdbc:mysql://172.18.0.16:3306/housing_db
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: midtob

    # EUREKA_SERVER: http://172.18.0.3:8761/eureka
    # KAFKA_BROKER_HOST_VIA_NGINX: midtob.com=172.18.0.2
    # KAFKA_SERVER: 172.18.0.2:9092
    USER_SERVICE: 172.18.0.33:9002
  script:
    - docker rm -f $DOCKER_CONTAINER
    - docker run -d 
      --name $DOCKER_CONTAINER 
      --network $INTERNAL_NETWORK_NAME 
      --ip $INTERNAL_STATIC_IP 
      --env PORT=$PORT 
      --env DATABASE_URL=$DATABASE_URL
      --env DATABASE_USERNAME=$DATABASE_USERNAME
      --env DATABASE_PASSWORD=$DATABASE_PASSWORD
      --env USER_SERVICE=$USER_SERVICE
      --cpus="$CPU_COUNT" 
      --cpu-shares=$CPU_SHARES $DOCKER_IMAGE
  tags:
    - housing-service
  only:
    - main

development_deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none

    INTERNAL_NETWORK_NAME: midtob-internal-devenv
    INTERNAL_STATIC_IP: 172.31.0.38
    PORT: 9006

    DATABASE_URL: jdbc:mysql://172.31.0.16:3306/housing_db
    DATABASE_USERNAME: root
    DATABASE_PASSWORD: midtob

    # EUREKA_SERVER: http://172.31.0.3:8761/eureka
    # KAFKA_BROKER_HOST_VIA_NGINX: midtob.com=172.31.0.2
    # KAFKA_SERVER: 172.31.0.2:9092
    USER_SERVICE: 172.31.0.33:9002
  script:
    - docker rm -f $DOCKER_CONTAINER
    - docker run -d 
      --name $DOCKER_CONTAINER 
      --network $INTERNAL_NETWORK_NAME 
      --ip $INTERNAL_STATIC_IP 
      --env PORT=$PORT 
      --env DATABASE_URL=$DATABASE_URL
      --env DATABASE_USERNAME=$DATABASE_USERNAME
      --env DATABASE_PASSWORD=$DATABASE_PASSWORD
      --env USER_SERVICE=$USER_SERVICE
      --cpus="$CPU_COUNT" 
      --cpu-shares=$CPU_SHARES $DOCKER_IMAGE
  tags:
    - housing-service
  only:
    - development