
api:
  prefix: api/v1
  user-service: ${USER_SERVICE:http://localhost:9002}
server:
  port: 9006


spring:
  application:
    name: housing-service
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://midtob.com:3306/housing_db?user=root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:midtob}
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            spatial:
              dialect:
                mysql:
                  MySQL56InnoDBSpatialDialect
#    hibernate:
#      ddl-auto: create-drop
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE